# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend
#   namespace: jamia-form
# spec:
#   selector:
#     app: frontend
#   ports:
#     - port: 3000
#       targetPort: 3000
#       protocol: TCP
#   type: ClusterIP


apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: jamia
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
